### PR TITLE
Get it to not crash

### PR DESCRIPTION
**Pull request by kwalcock**
There must still be an underlying problem to solve, but it is not crashing for me.  This uses a Seq (of distinct and sorted strings) instead of Set in much of the code. to avoid things like Set(1, 2, 3, 4).map(_ % 2).size == 4.  DQN shows a problem in that features cannot be moved.  I hope it works on computers other than mine.

### CODE REVIEW

**Comment by kwalcock** [comment]
@enoriega, can you try this out at your convenience?  Amogst the changes are a couple of small bug fixes that you will want to use even if it was to still crash.

**Comment by enoriega** [comment]
@kwalcock, I've been running it for significantly longer now and can confirm that it hasn't crashed on my computer either. I think it's safely to assume that the change from `Set` to `Seq` fixed the issue with DyNet.

I will declare victory one this. Thanks a lot for your help with this issue.

I am curious as if you have any insight on why changing the data structure while retaining the same code semantics messed up with DyNet internally.

**Comment by enoriega** [comment]
I am also deleting the `keith` branch and keeping the `dynet` branch. I fast-forwarded `dynet` to your commit, so they point to the same place.

**Comment by kwalcock** [comment]
If it doesn't crash for you, then maybe it can be a truce.  I think there is something wrong in dynet related to this code from the DQN:
```scala
  def evaluate(input: Seq[(WikiHopState, Seq[String], Seq[String])]): Tensor = {
    // It appears that this cannot be placed inside the loop below.
    val features = input.map { case (state, _, _) => vectorizeState(state) }

    val inputVectors = input.zip(features).map { case ((state, entityA, entityB), features) =>
      // val features = vectorizeState(state)
```
I looked through lots of the dynet code this morning, but nothing stuck out.  Except for this gotcha, it never crashed after the change from Set to Seq.  Maybe there is some code in the Scala wrapper that makes some assumptions that aren't valid for a Set.  Perhaps there is a problem with memory management for aliased objects.  EmbeddingsHelper.lookup seems a little scary when used on a set.  Two different strings could be the same after sanitization and I'm not sure whether the resulting Expressions will be the same.  Two different strings could both be OOV and perhaps on is eliminated in the Set.  It *seems* like set.toSeq can give iterators that produce values in different order.  Anyway, lots might go wrong, so maybe better to avoid it.

Changing only the line above and not the Set to Seq is not sufficient to prevent the crash.  There must be some interaction between the problems.

You program might not be getting the same answer as before.  Treat it sceptically.

**Comment by kwalcock** [comment]
P.P.S. I forgot to replace the `max` in TrainFr:
```scala
    val nextStateValues = // TODO figure out this correctly, this considers the state values of all the possible entity combinations, not just only of  the ones with the top entity
      max{
```

**Comment by enoriega** [comment]
I see. I was using sets to keep the uniqueness of the terms in an efficient way, but using sequences shouldn't hurt that much. You used `distintct` which should be enough to enforce the constraint that I am seeking. Nonetheless I'm going to test it before merging it to `master`. Thanks for it again!

**Pull request merged**
